---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/blog"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/restaurant-website"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/tv-shows-catalog/client"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/tv-shows-catalog/server"
    schedule:
      interval: "monthly"
...
