version: '3.8'

services:
  php:
    container_name: php
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
