FROM nginx:1-alpine
COPY .docker/nginx/grilli.com.conf /etc/nginx/conf.d/default.conf
HEALTHCHECK --interval=10s --timeout=5s \
    CMD [ "nc", "-z", "127.0.0.1", "80" ]
CMD ["nginx", "-g", "daemon off;"]