version: '3.8'

services:
  php:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "${PHP_DEV_PORT}:80"
    volumes:
      - ./public:/var/www/html/public:rw
      - ./src:/var/www/html/src:rw
      - ./config:/var/www/html/config:rw
      - ./templates:/var/www/html/templates:rw
