# Production
version: '3.8'
services:
  php:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./public:/var/www/html/public:rw
      - ./src:/var/www/html/src:rw
      - ./config:/var/www/html/config:rw
      - ./templates:/var/www/html/templates:rw

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT}:8080"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./public:/var/www/html/public:ro
      - ./config/:/var/www/html/config:ro
      - ./templates:/var/www/html/templates:ro
      - ./src:/var/www/html/src:ro
    depends_on:
      php:
        condition: service_healthy
