version: '3.8'

services:
  php:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:rw

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT}:8080"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - .:/var/www/html:ro
    depends_on:
      php:
        condition: service_healthy
