FROM nginxinc/nginx-unprivileged:1-alpine
COPY .docker/nginx/grilli.com.conf /etc/nginx/conf.d/default.conf
HEALTHCHECK --interval=1m --timeout=3s \
    CMD curl --fail http://localhost/health || exit 1
