version: '3.8'

services:
  php:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "${PHP_DEV_PORT}:80"
    volumes:
      - .:/var/www/html
