name: Build restaurant

on:
  pull_request:
    paths:
      - 'restaurant-website/**'

permissions:
  contents: read

jobs:
    build-dev:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build Dockerfiles
              run: |
                docker build -t restaurant ./restaurant-website --target dev
    build-prod:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build Dockerfiles
              run: |
                docker build -t restaurant ./restaurant-website --target prod
