name: Build restaurant

on:
  pull_request:
    paths:
      - 'restaurant-website/**'
      - '.github/workflows/build-restaurant.yml'

permissions:
  contents: read

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Build
        id: build_image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: .
          file: ./restaurant-website/Dockerfile
          target: dev
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false

  build-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Build
        id: build_image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: .
          file: ./restaurant-website/Dockerfile
          target: prod
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
