# Production
version: '3.8'
services:
  server:
    image: server-backend
    build:
      context: ./server
      target: prod
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PORT=${BACK_PORT}

  client:
    image: client-frontend
    build:
      context: ./client
      target: prod
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PORT=${FRONT_PROD_PORT}
      - API_BASE_URL=${API_BASE_URL}

  caddy:
    image: caddy-server
    build:
      context: ./caddy
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - FRONT_PORT=${FRONT_PROD_PORT}
      - BACK_PORT=${BACK_PORT}
    ports:
      - "${CADDY_HTTP_PORT}:80"
      - "${CADDY_HTTPS_PORT}:443"
    depends_on:
      - server
      - client
