version: '3.8'
services:
  server:
    image: server-backend
    build:
      context: ./server
      target: dev
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
        - /app/node_modules
        - ./server:/app:rw
    ports:
      - "${BACK_PORT}:${BACK_PORT}"

  client:
    image: client-frontend
    build:
      context: ./client
      target: dev
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      - API_BASE_URL=${API_BASE_URL}
    volumes:
        - /app/node_modules
        - ./client:/app:rw
    ports:
      - "${FRONT_DEV_PORT}:${FRONT_DEV_PORT}"
    depends_on:
      - server
